# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beltbuckle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='')),
                ('desc', models.TextField()),
                ('category', models.CharField(choices=[('Pin Buckle', 'Pin Buckle'), ('Double Rings', 'Double Rings'), ('Alloy Dress', 'Alloy Dress'), ('Simple Pin', 'Simple Pin'), ('Crystal Metal', 'Crystal Metal'), ('Clasp', 'Clasp'), ('Auto', 'Auto')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='')),
                ('desc', models.TextField()),
                ('category', models.CharField(choices=[('Metal', 'Metal'), ('Plastic', 'Plastic'), ('Wooden', 'Wooden'), ('Bone Horn', 'Bone Horn'), ('Polyester', 'Polyester'), ('Shell', 'Shell'), ('Cloth', 'Cloth'), ('Leather', 'Leather'), ('Thread', 'Thread'), ('Coconut shell', 'Coconut shell'), ('Ceramic Garment', 'Ceramic Garment'), ('Lace', 'Lace'), ('Resin', 'Resin')], max_length=100)),
                ('style', models.CharField(choices=[('Two Hole', 'Two Hole'), ('Four Hole', 'Four Hole'), ('Press', 'Press'), ('Shank', 'Shank'), ('Hook and Eye', 'Hook and Eye'), ('Coat', 'Coat'), ('Shirt', 'Shirt'), ('Cardigan', 'Cardigan'), ('Toggle', 'Toggle'), ('Decorative', 'Decorative')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='')),
                ('desc', models.TextField()),
                ('category', models.CharField(choices=[('Cotton', 'Cotton'), ('Polyester', 'Polyester'), ('Nylon', 'Nylon'), ('Elastic', 'Elastic'), ('Cotton Fabric', 'Cotton Fabric'), ('Woven Embroidery', 'Woven Embroidery'), ('Woven Embroidery Fabric', 'Woven Embroidery Fabric'), ('Chest', 'Chest'), ('Shoulder', 'Shoulder')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='')),
                ('desc', models.TextField()),
                ('category', models.CharField(choices=[('Metal', 'Metal'), ('Plastic', 'Plastic'), ('Nylon', 'Nylon'), ('Rhinestone', 'Rhinestone')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Waistbelt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='')),
                ('desc', models.TextField()),
                ('category', models.CharField(choices=[('Genuine Leather', 'Genuine Leather'), ('PU Leather', 'PU Leather'), ('Silicon Rubber', 'Silicon Rubber'), ('Fancy Metal', 'Fancy Metal'), ('Elastic', 'Elastic'), ('Rhinestone', 'Rhinestone'), ('Fabric', 'Fabric'), ('Canvas', 'Canvas')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Zipper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='')),
                ('desc', models.TextField()),
                ('category', models.CharField(choices=[('Metal', 'Metal'), ('Plastic', 'Plastic'), ('Nylon', 'Nylon'), ('Rhinestone', 'Rhinestone')], max_length=100)),
            ],
        ),
    ]
