# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170803_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(choices=[('Beltbuckle', 'Beltbuckle'), ('Button', 'Button'), ('Lace', 'Lace'), ('Zipper', 'Zipper'), ('Slider', 'Slider'), ('Waistbelt', 'Waistbelt')], max_length=50),
        ),
    ]
