# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170803_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='category',
            field=models.CharField(choices=[('Metal', 'Metal'), ('Plastic', 'Plastic'), ('Wooden', 'Wooden'), ('Bone Horn', 'Bone Horn'), ('Polyester', 'Polyester'), ('Shell', 'Shell'), ('Cloth', 'Cloth'), ('Leather', 'Leather'), ('Thread', 'Thread'), ('Coconut Shell', 'Coconut Shell'), ('Ceramic Garment', 'Ceramic Garment'), ('Lace', 'Lace'), ('Resin', 'Resin')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(choices=[('Waistbelt', 'Waistbelt'), ('Beltbuckle', 'Beltbuckle'), ('Lace', 'Lace'), ('Zipper', 'Zipper'), ('Slider', 'Slider'), ('Button', 'Button')], max_length=50),
        ),
    ]
