# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 06:00
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170808_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='style',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Two Hole', 'Two Hole'), ('Four Hole', 'Four Hole'), ('Press', 'Press'), ('Shank', 'Shank'), ('Hook and Eye', 'Hook and Eye'), ('Coat', 'Coat'), ('Shirt', 'Shirt'), ('Cardigan', 'Cardigan'), ('Toggle', 'Toggle'), ('Decorative', 'Decorative')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(choices=[('Zipper', 'Zipper'), ('Beltbuckle', 'Beltbuckle'), ('Button', 'Button'), ('Slider', 'Slider'), ('Lace', 'Lace'), ('Waistbelt', 'Waistbelt')], max_length=50),
        ),
    ]
