# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-09 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20171009_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(choices=[('Beltbuckle', 'Beltbuckle'), ('Waistbelt', 'Waistbelt'), ('Slider', 'Slider'), ('Zipper', 'Zipper'), ('Lace', 'Lace'), ('Button', 'Button')], max_length=50),
        ),
    ]
