# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-15 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20171009_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(choices=[('Waistbelt', 'Waistbelt'), ('Button', 'Button'), ('Beltbuckle', 'Beltbuckle'), ('Lace', 'Lace'), ('Zipper', 'Zipper'), ('Slider', 'Slider')], max_length=50),
        ),
        migrations.AlterField(
            model_name='zipper',
            name='category',
            field=models.CharField(choices=[('Metal', 'Metal'), ('Plastic', 'Plastic'), ('Vislon', 'Vislon')], max_length=100),
        ),
    ]
