# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-17 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20171015_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beltbuckle',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='beltbuckle',
            name='img',
        ),
        migrations.RemoveField(
            model_name='button',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='button',
            name='img',
        ),
        migrations.RemoveField(
            model_name='lace',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='lace',
            name='img',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='img',
        ),
        migrations.RemoveField(
            model_name='waistbelt',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='waistbelt',
            name='img',
        ),
        migrations.RemoveField(
            model_name='zipper',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='zipper',
            name='img',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(choices=[('Waistbelt', 'Waistbelt'), ('Button', 'Button'), ('Slider', 'Slider'), ('Lace', 'Lace'), ('Zipper', 'Zipper'), ('Beltbuckle', 'Beltbuckle')], max_length=50),
        ),
    ]
