# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-17 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20171017_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(choices=[('Lace', 'Lace'), ('Waistbelt', 'Waistbelt'), ('Zipper', 'Zipper'), ('Slider', 'Slider'), ('Beltbuckle', 'Beltbuckle'), ('Button', 'Button')], max_length=50),
        ),
    ]
