# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-22 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20171019_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='style',
            field=models.CharField(choices=[('Two Hole', 'Two Hole'), ('Four Hole', 'Four Hole'), ('Press', 'Press'), ('Shank', 'Shank'), ('Hook and Eye', 'Hook and Eye'), ('Coat', 'Coat'), ('Shirt', 'Shirt'), ('Cardigan', 'Cardigan'), ('Toggle', 'Toggle'), ('Decorative', 'Decorative')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(choices=[('Waistbelt', 'Waistbelt'), ('Slider', 'Slider'), ('Button', 'Button'), ('Lace', 'Lace'), ('Zipper', 'Zipper'), ('Beltbuckle', 'Beltbuckle')], max_length=50),
        ),
    ]
