# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-02 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20171030_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beltbuckle',
            name='category',
            field=models.CharField(choices=[('Pin Buckle', 'Pin Buckle'), ('Double Rings', 'Double Rings'), ('Alloy', 'Alloy'), ('Crystal Metal', 'Crystal Metal'), ('Auto', 'Auto')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(choices=[('Waistbelt', 'Waistbelt'), ('Slider', 'Slider'), ('Beltbuckle', 'Beltbuckle'), ('Zipper', 'Zipper'), ('Lace', 'Lace'), ('Button', 'Button')], max_length=50),
        ),
    ]
