# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-09 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20171102_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teammember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(choices=[('Waistbelt', 'Waistbelt'), ('Beltbuckle', 'Beltbuckle'), ('Button', 'Button'), ('Zipper', 'Zipper'), ('Slider', 'Slider'), ('Lace', 'Lace')], max_length=50),
        ),
    ]
