# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-09 06:21
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20171109_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(choices=[('Zipper', 'Zipper'), ('Waistbelt', 'Waistbelt'), ('Button', 'Button'), ('Beltbuckle', 'Beltbuckle'), ('Lace', 'Lace'), ('Slider', 'Slider')], max_length=50),
        ),
        migrations.AlterField(
            model_name='zipper',
            name='category',
            field=models.CharField(choices=[('Metal', 'Metal'), ('Vislon', 'Vislon'), ('Nylon', 'Nylon')], max_length=100),
        ),
        migrations.AlterField(
            model_name='zipper',
            name='style',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Open-end', 'Open-end'), ('Close-end', 'Close-end'), ('Two-way', 'Two-way'), ('Coil', 'Coil'), ('Invisible', 'Invisible')], max_length=41),
        ),
    ]
